// <auto-generated />
namespace Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test16 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test16));
        
        string IMigrationMetadata.Id
        {
            get { return "201703081457258_test16"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
