// <auto-generated />
namespace Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LeaveManagement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LeaveManagement));
        
        string IMigrationMetadata.Id
        {
            get { return "201701120910336_LeaveManagement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
