//var arLang = function () {
//    var d = [
//        { id: "af", name: "أفريقانى" },
//        //{id:"af-NA",name:"Afrikaans (Namibia)"},
//        { id: "af-ZA", name: "أفريقانى" },
//        //{id:"agq-CM",name:"Aghem (Cameroon)"},
//        //{id:"ak-GH",name:"Akan (Ghana)"}, 
//        { id: "am", name: "Amharic" }, ]
//}
var lang = function () {

    function getList(culture) {

        var d = [
                //{id:"ar-EG",name:"Default"},
                //{id:"aa-DJ",name:"Afar (Djibouti)"},
                //{id:"aa-ER",name:"Afar (Eritrea)"},
                //{id:"aa-ET",name:"Afar (Ethiopia)"},
                { id: "af", name: "Afrikaans" },
                //{id:"af-NA",name:"Afrikaans (Namibia)"},
                { id: "af-ZA", name: "Afrikaans (South Africa)" },
                //{id:"agq-CM",name:"Aghem (Cameroon)"},
                //{id:"ak-GH",name:"Akan (Ghana)"},
                { id: "am", name: "Amharic" },
                { id: "am-ET", name: "Amharic (Ethiopia)" },
                //{id:"ar",name:"Arabic"},
                //{id:"ar-001",name:"Arabic (World)"},
                { id: "ar-AE", name: "Arabic (U.A.E.)", arName: "عربي (الامارات)" },
                { id: "ar-BH", name: "Arabic (Bahrain)", arName: "عربي (البحرين)" },
                //{id:"ar-DJ",name:"Arabic (Djibouti)"},
                { id: "ar-DZ", name: "Arabic (Algeria)", arName: "عربي (الجزائر)" },
                { id: "ar-EG", name: "Arabic (Egypt)", arName: "عربي (مصر)" },
                //{id:"ar-ER",name:"Arabic (Eritrea)"},
                { id: "ar-IQ", name: "Arabic (Iraq)", arName: "عربي (العراق)" },
                { id: "ar-JO", name: "Arabic (Jordan)", arName: "عربي (الأردن)" },
                //{id:"ar-KM",name:"Arabic (Comoros)"},
                { id: "ar-KW", name: "Arabic (Kuwait)", arName: "عربي (الكويت)" },
                { id: "ar-LB", name: "Arabic (Lebanon)", arName: "عربي (لبنان)" },
                { id: "ar-LY", name: "Arabic (Libya)", arName: "عربي (ليبيا)" },
                { id: "ar-MA", name: "Arabic (Morocco)", arName: "عربي (المغرب)" },
                //{id:"ar-MR",name:"Arabic (Mauritania)"},
                { id: "ar-OM", name: "Arabic (Oman)", arName: "عربي (عمان)" },
                //{id:"ar-PS",name:"Arabic (Palestinian Authority)"},
                { id: "ar-QA", name: "Arabic (Qatar)", arName: "عربي (قطر)" },
                { id: "ar-SA", name: "Arabic (Saudi Arabia)", arName: "عربي (السعودية)" },
                //{id:"ar-SD",name:"Arabic (Sudan)"},
                //{id:"ar-SO",name:"Arabic (Somalia)"},
                //{id:"ar-SS",name:"Arabic (South Sudan)"},
                { id: "ar-SY", name: "Arabic (Syria)", arName: "عربي (سوريا)" },
                //{id:"ar-TD",name:"Arabic (Chad)"},
                { id: "ar-TN", name: "Arabic (Tunisia)", arName: "عربي (تونس)" },
                { id: "ar-YE", name: "Arabic (Yemen)", arName: "عربي (اليمن)" },
                { id: "arn", name: "Mapudungun" },
                { id: "arn-CL", name: "Mapudungun (Chile)" },
                { id: "as", name: "Assamese" },
                { id: "as-IN", name: "Assamese (India)" },
                //{id:"asa-TZ",name:"Asu (Tanzania)"},
                //{id:"ast-ES",name:"Asturian (Spain)"},
                { id: "az", name: "Azerbaijani" },
                { id: "az-Cyrl", name: "Azerbaijani (Cyrillic)" },
                { id: "az-Cyrl-AZ", name: "Azerbaijani (Cyrillic, Azerbaijan)" },
                { id: "az-Latn", name: "Azerbaijani (Latin)" },
                { id: "az-Latn-AZ", name: "Azerbaijani (Latin, Azerbaijan)" },
                { id: "ba", name: "Bashkir" },
                { id: "ba-RU", name: "Bashkir (Russia)" },
                //{id:"bas-CM",name:"Basaa (Cameroon)"},
                { id: "be", name: "Belarusian" },
                { id: "be-BY", name: "Belarusian (Belarus)" },
                //{id:"bem-ZM",name:"Bemba (Zambia)"},
                //{id:"bez-TZ",name:"Bena (Tanzania)"},
                { id: "bg", name: "Bulgarian" },
                { id: "bg-BG", name: "Bulgarian (Bulgaria)" },
                //{id:"bin",name:"Edo"},
                //{id:"bin-NG",name:"Edo (Nigeria)"},
                //{id:"bm-Latn-ML",name:"Bambara (Latin, Mali)"},
                { id: "bn", name: "Bangla" },
                { id: "bn-BD", name: "Bangla (Bangladesh)" },
                //{id:"bn-IN",name:"Bangla (India)"},
                { id: "bo", name: "Tibetan" },
                { id: "bo-CN", name: "Tibetan (PRC)" },
                //{id:"bo-IN",name:"Tibetan (India)"},
                { id: "br", name: "Breton" },
                { id: "br-FR", name: "Breton (France)" },
                //{id:"brx-IN",name:"Bodo (India)"},
                { id: "bs", name: "Bosnian" },
                { id: "bs-Cyrl", name: "Bosnian (Cyrillic)" },
                { id: "bs-Cyrl-BA", name: "Bosnian (Cyrillic, Bosnia and Herzegovina)" },
                { id: "bs-Latn", name: "Bosnian (Latin)" },
                { id: "bs-Latn-BA", name: "Bosnian (Latin, Bosnia and Herzegovina)" },
                //{id:"byn-ER",name:"Blin (Eritrea)"},
                { id: "ca", name: "Catalan" },
                //{id:"ca-AD",name:"Catalan (Andorra)"},
                { id: "ca-ES", name: "Catalan (Catalan)" },
                { id: "ca-ES-valencia", name: "Valencian (Spain)" },
                //{id:"ca-FR",name:"Catalan (France)"},
                //{id:"ca-IT",name:"Catalan (Italy)"},
                //{id:"ce-RU",name:"Chechen (Russia)"},
                //{id:"cgg-UG",name:"Chiga (Uganda)"},
                { id: "chr", name: "Cherokee" },
                { id: "chr-Cher", name: "Cherokee (Cherokee)" },
                { id: "chr-Cher-US", name: "Cherokee (Cherokee)" },
                { id: "co", name: "Corsican" },
                { id: "co-FR", name: "Corsican (France)" },
                { id: "cs", name: "Czech" },
                { id: "cs-CZ", name: "Czech (Czech Republic)" },
                //{id:"cu-RU",name:"Church Slavic (Russia)"},
                { id: "cy", name: "Welsh" },
                { id: "cy-GB", name: "Welsh (United Kingdom)" },
                { id: "da", name: "Danish" },
                { id: "da-DK", name: "Danish (Denmark)" },
                //{id:"da-GL",name:"Danish (Greenland)"},
                //{id:"dav-KE",name:"Taita (Kenya)"},
                { id: "de", name: "German" },
                { id: "de-AT", name: "German (Austria)" },
                //{id:"de-BE",name:"German (Belgium)"},
                { id: "de-CH", name: "German (Switzerland)" },
                { id: "de-DE", name: "German (Germany)" },
                { id: "de-LI", name: "German (Liechtenstein)" },
                { id: "de-LU", name: "German (Luxembourg)" },
                //{id:"dje-NE",name:"Zarma (Niger)"},
                { id: "dsb", name: "Lower Sorbian" },
                { id: "dsb-DE", name: "Lower Sorbian (Germany)" },
                //{id:"dua-CM",name:"Duala (Cameroon)"},
                { id: "dv", name: "Divehi" },
                { id: "dv-MV", name: "Divehi (Maldives)" },
                //{id:"dyo-SN",name:"Jola-Fonyi (Senegal)"},
                //{id:"dz-BT",name:"Dzongkha (Bhutan)"},
                //{id:"ebu-KE",name:"Embu (Kenya)"},
                //{id:"ee-GH",name:"Ewe (Ghana)"},
                //{id:"ee-TG",name:"Ewe (Togo)"},
                { id: "el", name: "Greek" },
                //{id:"el-CY",name:"Greek (Cyprus)"},
                { id: "el-GR", name: "Greek (Greece)" },
                //{id:"en",name:"English"},
                //{id:"en-001",name:"English (World)"},
                { id: "en-029", name: "English (Caribbean)" },
                //{id:"en-150",name:"English (Europe)"},
                //{id:"en-AG",name:"English (Antigua and Barbuda)"},
                //{id:"en-AI",name:"English (Anguilla)"},
                //{id:"en-AS",name:"English (American Samoa)"},
                //{id:"en-AT",name:"English (Austria)"},
                { id: "en-AU", name: "English (Australia)" },
                //{id:"en-BB",name:"English (Barbados)"},
                //{id:"en-BE",name:"English (Belgium)"},
                //{id:"en-BI",name:"English (Burundi)"},
                //{id:"en-BM",name:"English (Bermuda)"},
                //{id:"en-BS",name:"English (Bahamas)"},
                //{id:"en-BW",name:"English (Botswana)"},
                { id: "en-BZ", name: "English (Belize)" },
                { id: "en-CA", name: "English (Canada)" },
                //{id:"en-CC",name:"English (Cocos [Keeling] Islands)"},
                //{id:"en-CH",name:"English (Switzerland)"},
                //{id:"en-CK",name:"English (Cook Islands)"},
                //{id:"en-CM",name:"English (Cameroon)"},
                //{id:"en-CX",name:"English (Christmas Island)"},
                //{id:"en-CY",name:"English (Cyprus)"},
                //{id:"en-DE",name:"English (Germany)"},
                //{id:"en-DK",name:"English (Denmark)"},
                //{id:"en-DM",name:"English (Dominica)"},
                //{id:"en-ER",name:"English (Eritrea)"},
                //{id:"en-FI",name:"English (Finland)"},
                //{id:"en-FJ",name:"English (Fiji)"},
                //{id:"en-FK",name:"English (Falkland Islands)"},
                //{id:"en-FM",name:"English (Micronesia)"},
                { id: "en-GB", name: "English (United Kingdom)", arName: "انجليزي (المملكة المتحدة)" },
                //{id:"en-GD",name:"English (Grenada)"},
                //{id:"en-GG",name:"English (Guernsey)"},
                //{id:"en-GH",name:"English (Ghana)"},
                //{id:"en-GI",name:"English (Gibraltar)"},
                //{id:"en-GM",name:"English (Gambia)"},
                //{id:"en-GU",name:"English (Guam)"},
                //{id:"en-GY",name:"English (Guyana)"},
                { id: "en-HK", name: "English (Hong Kong SAR)" },
                //{id:"en-ID",name:"English (Indonesia)"},
                { id: "en-IE", name: "English (Ireland)" },
                //{id:"en-IM",name:"English (Isle of Man)"},
                { id: "en-IN", name: "English (India)" },
                //{id:"en-IO",name:"English (British Indian Ocean Territory)"},
                //{id:"en-JE",name:"English (Jersey)"},
                { id: "en-JM", name: "English (Jamaica)" },
                //{id:"en-KE",name:"English (Kenya)"},
                //{id:"en-KI",name:"English (Kiribati)"},
                //{id:"en-KN",name:"English (Saint Kitts and Nevis)"},
                //{id:"en-KY",name:"English (Cayman Islands)"},
                //{id:"en-LC",name:"English (Saint Lucia)"},
                //{id:"en-LR",name:"English (Liberia)"},
                //{id:"en-LS",name:"English (Lesotho)"},
                //{id:"en-MG",name:"English (Madagascar)"},
                //{id:"en-MH",name:"English (Marshall Islands)"},
                //{id:"en-MO",name:"English (Macao SAR)"},
                //{id:"en-MP",name:"English (Northern Mariana Islands)"},
                //{id:"en-MS",name:"English (Montserrat)"},
                //{id:"en-MT",name:"English (Malta)"},
                //{id:"en-MU",name:"English (Mauritius)"},
                //{id:"en-MW",name:"English (Malawi)"},
                { id: "en-MY", name: "English (Malaysia)" },
                //{id:"en-NA",name:"English (Namibia)"},
                //{id:"en-NF",name:"English (Norfolk Island)"},
                //{id:"en-NG",name:"English (Nigeria)"},
                //{id:"en-NL",name:"English (Netherlands)"},
                //{id:"en-NR",name:"English (Nauru)"},
                //{id:"en-NU",name:"English (Niue)"},
                { id: "en-NZ", name: "English (New Zealand)" },
                //{id:"en-PG",name:"English (Papua New Guinea)"},
                { id: "en-PH", name: "English (Republic of the Philippines)" },
                //{id:"en-PK",name:"English (Pakistan)"},
                //{id:"en-PN",name:"English (Pitcairn Islands)"},
                //{id:"en-PR",name:"English (Puerto Rico)"},
                //{id:"en-PW",name:"English (Palau)"},
                //{id:"en-RW",name:"English (Rwanda)"},
                //{id:"en-SB",name:"English (Solomon Islands)"},
                //{id:"en-SC",name:"English (Seychelles)"},
                //{id:"en-SD",name:"English (Sudan)"},
                //{id:"en-SE",name:"English (Sweden)"},
                { id: "en-SG", name: "English (Singapore)" },
                //{id:"en-SH",name:"English (St Helena, Ascension, Tristan da Cunha)"},
                //{id:"en-SI",name:"English (Slovenia)"},
                //{id:"en-SL",name:"English (Sierra Leone)"},
                //{id:"en-SS",name:"English (South Sudan)"},
                //{id:"en-SX",name:"English (Sint Maarten)"},
                //{id:"en-SZ",name:"English (Swaziland)"},
                //{id:"en-TC",name:"English (Turks and Caicos Islands)"},
                //{id:"en-TK",name:"English (Tokelau)"},
                //{id:"en-TO",name:"English (Tonga)"},
                { id: "en-TT", name: "English (Trinidad and Tobago)" },
                //{id:"en-TV",name:"English (Tuvalu)"},
                //{id:"en-TZ",name:"English (Tanzania)"},
                //{id:"en-UG",name:"English (Uganda)"},
                //{id:"en-UM",name:"English (US Minor Outlying Islands)"},
                { id: "en-US", name: "English (United States)", arName: "انجليزي (الولايات المتحدة الأمريكية)" },
                //{id:"en-VC",name:"English (Saint Vincent and the Grenadines)"},
                //{id:"en-VG",name:"English (British Virgin Islands)"},
                //{id:"en-VI",name:"English (US Virgin Islands)"},
                //{id:"en-VU",name:"English (Vanuatu)"},
                //{id:"en-WS",name:"English (Samoa)"},
                { id: "en-ZA", name: "English (South Africa)" },
                //{id:"en-ZM",name:"English (Zambia)"},
                { id: "en-ZW", name: "English (Zimbabwe)" },
                //{id:"eo-001",name:"Esperanto (World)"},
                { id: "es", name: "Spanish" },
                { id: "es-419", name: "Spanish (Latin America)" },
                { id: "es-AR", name: "Spanish (Argentina)" },
                { id: "es-BO", name: "Spanish (Bolivia)" },
                { id: "es-CL", name: "Spanish (Chile)" },
                { id: "es-CO", name: "Spanish (Colombia)" },
                { id: "es-CR", name: "Spanish (Costa Rica)" },
                //{id:"es-CU",name:"Spanish (Cuba)"},
                { id: "es-DO", name: "Spanish (Dominican Republic)" },
                { id: "es-EC", name: "Spanish (Ecuador)" },
                { id: "es-ES", name: "Spanish (Spain)" },
                //{id:"es-GQ",name:"Spanish (Equatorial Guinea)"},
                { id: "es-GT", name: "Spanish (Guatemala)" },
                { id: "es-HN", name: "Spanish (Honduras)" },
                { id: "es-MX", name: "Spanish (Mexico)" },
                { id: "es-NI", name: "Spanish (Nicaragua)" },
                { id: "es-PA", name: "Spanish (Panama)" },
                { id: "es-PE", name: "Spanish (Peru)" },
                //{id:"es-PH",name:"Spanish (Philippines)"},
                { id: "es-PR", name: "Spanish (Puerto Rico)" },
                { id: "es-PY", name: "Spanish (Paraguay)" },
                { id: "es-SV", name: "Spanish (El Salvador)" },
                { id: "es-US", name: "Spanish (United States)" },
                { id: "es-UY", name: "Spanish (Uruguay)" },
                { id: "es-VE", name: "Spanish (Bolivarian Republic of Venezuela)" },
                { id: "et", name: "Estonian" },
                { id: "et-EE", name: "Estonian (Estonia)" },
                { id: "eu", name: "Basque" },
                { id: "eu-ES", name: "Basque (Basque)" },
                //{id:"ewo-CM",name:"Ewondo (Cameroon)"},
                { id: "fa", name: "Persian" },
                { id: "fa fa-IR", name: "Persian (Iran)" },
                { id: "ff", name: "Fulah" },
                //{id:"ff-CM",name:"Fulah (Cameroon)"},
                //{id:"ff-GN",name:"Fulah (Guinea)"},
                { id: "ff-Latn", name: "Fulah (Latin)" },
                { id: "ff-Latn-SN", name: "Fulah (Latin, Senegal)" },
                //{id:"ff-MR",name:"Fulah (Mauritania)"},
                //{id:"ff-NG",name:"Fulah (Nigeria)"},
                { id: "fi", name: "Finnish" },
                { id: "fi-FI", name: "Finnish (Finland)" },
                { id: "fil", name: "Filipino" },
                { id: "fil-PH", name: "Filipino (Philippines)" },
                { id: "fo", name: "Faroese" },
                //{id:"fo-DK",name:"Faroese (Denmark)"},
                { id: "fo-FO", name: "Faroese (Faroe Islands)" },
                { id: "fr", name: "French" },
                //{id:"fr-029",name:"French (Caribbean)"},
                { id: "fr-BE", name: "French (Belgium)" },
                //{id:"fr-BF",name:"French (Burkina Faso)"},
                //{id:"fr-BI",name:"French (Burundi)"},
                //{id:"fr-BJ",name:"French (Benin)"},
                //{id:"fr-BL",name:"French (Saint Barthélemy)"},
                { id: "fr-CA", name: "French (Canada)" },
                { id: "fr-CD", name: "French (Congo DRC)" },
                //{id:"fr-CF",name:"French (Central African Republic)"},
                //{id:"fr-CG",name:"French (Congo)"},
                { id: "fr-CH", name: "French (Switzerland)" },
                { id: "fr-CI", name: "French (Côte d’Ivoire)" },
                { id: "fr-CM", name: "French (Cameroon)" },
                //{id:"fr-DJ",name:"French (Djibouti)"},
                //{id:"fr-DZ",name:"French (Algeria)"},
                { id: "fr-FR", name: "French (France)" },
                //{id:"fr-GA",name:"French (Gabon)"},
                //{id:"fr-GF",name:"French (French Guiana)"},
                //{id:"fr-GN",name:"French (Guinea)"},
                //{id:"fr-GP",name:"French (Guadeloupe)"},
                //{id:"fr-GQ",name:"French (Equatorial Guinea)"},
                { id: "fr-HT", name: "French (Haiti)" },
                //{id:"fr-KM",name:"French (Comoros)"},
                { id: "fr-LU", name: "French (Luxembourg)" },
                { id: "fr-MA", name: "French (Morocco)" },
                { id: "fr-MC", name: "French (Monaco)" },
                //{id:"fr-MF",name:"French (Saint Martin)"},
                //{id:"fr-MG",name:"French (Madagascar)"},
                { id: "fr-ML", name: "French (Mali)" },
                //{id:"fr-MQ",name:"French (Martinique)"},
                //{id:"fr-MR",name:"French (Mauritania)"},
                //{id:"fr-MU",name:"French (Mauritius)"},
                //{id:"fr-NC",name:"French (New Caledonia)"},
                //{id:"fr-NE",name:"French (Niger)"},
                //{id:"fr-PF",name:"French (French Polynesia)"},
                //{id:"fr-PM",name:"French (Saint Pierre and Miquelon)"},
                { id: "fr-RE", name: "French (Reunion)" },
                //{id:"fr-RW",name:"French (Rwanda)"},
                //{id:"fr-SC",name:"French (Seychelles)"},
                { id: "fr-SN", name: "French (Senegal)" },
                //{id:"fr-SY",name:"French (Syria)"},
                //{id:"fr-TD",name:"French (Chad)"},
                //{id:"fr-TG",name:"French (Togo)"},
                //{id:"fr-TN",name:"French (Tunisia)"},
                //{id:"fr-VU",name:"French (Vanuatu)"},
                //{id:"fr-WF",name:"French (Wallis and Futuna)"},
                //{id:"fr-YT",name:"French (Mayotte)"},
                //{id:"fur-IT",name:"Friulian (Italy)"},
                { id: "fy", name: "Frisian" },
                { id: "fy-NL", name: "Frisian (Netherlands)" },
                { id: "ga", name: "Irish" },
                { id: "ga-IE", name: "Irish (Ireland)" },
                { id: "gd", name: "Scottish Gaelic" },
                { id: "gd-GB", name: "Scottish Gaelic (United Kingdom)" },
                { id: "gl", name: "Galician" },
                { id: "gl-ES", name: "Galician (Galician)" },
                { id: "gn", name: "Guarani" },
                { id: "gn-PY", name: "Guarani (Paraguay)" },
                { id: "gsw", name: "Alsatian" },
                //{id:"gsw-CH",name:"Alsatian (Switzerland)"},
                { id: "gsw-FR", name: "Alsatian (France)" },
                //{id:"gsw-LI",name:"Alsatian (Liechtenstein)"},
                { id: "gu", name: "Gujarati" },
                { id: "gu-IN", name: "Gujarati (India)" },
                //{id:"guz-KE",name:"Gusii (Kenya)"},
                //{id:"gv-IM",name:"Manx (Isle of Man)"},
                { id: "ha", name: "Hausa" },
                { id: "ha-Latn", name: "Hausa (Latin)" },
                //{id:"ha-Latn-GH",name:"Hausa (Latin, Ghana)"},
                //{id:"ha-Latn-NE",name:"Hausa (Latin, Niger)"},
                { id: "ha-Latn-NG", name: "Hausa (Latin, Nigeria)" },
                { id: "haw", name: "Hawaiian" },
                { id: "haw-US", name: "Hawaiian (United States)" },
                { id: "hi", name: "Hindi" },
                { id: "hi-IN", name: "Hindi (India)" },
                { id: "hr", name: "Croatian" },
                { id: "hr-BA", name: "Croatian (Latin, Bosnia and Herzegovina)" },
                { id: "hr-HR", name: "Croatian (Croatia)" },
                { id: "hsb", name: "Upper Sorbian" },
                { id: "hsb-DE", name: "Upper Sorbian (Germany)" },
                { id: "hu", name: "Hungarian" },
                { id: "hu-HU", name: "Hungarian (Hungary)" },
                { id: "hy", name: "Armenian" },
                { id: "hy-AM", name: "Armenian (Armenia)" },
                //{id:"ia-001",name:"Interlingua (World)"},
                //{id:"ia-FR",name:"Interlingua (France)"},
                //{id:"ibb",name:"Ibibio"},
                //{id:"ibb-NG",name:"Ibibio (Nigeria)"},
                { id: "id", name: "Indonesian" },
                { id: "id-ID", name: "Indonesian (Indonesia)" },
                { id: "ig", name: "Igbo" },
                { id: "ig-NG", name: "Igbo (Nigeria)" },
                { id: "ii", name: "Yi" },
                { id: "ii-CN", name: "Yi (PRC)" },
                { id: "is", name: "Icelandic" },
                { id: "is-IS", name: "Icelandic (Iceland)" },
                { id: "it", name: "Italian" },
                { id: "it-CH", name: "Italian (Switzerland)" },
                { id: "it-IT", name: "Italian (Italy)" },
                //{id:"it-SM",name:"Italian (San Marino)"},
                { id: "iu", name: "Inuktitut" },
                { id: "iu-Cans", name: "Inuktitut (Syllabics)" },
                { id: "iu-Cans-CA", name: "Inuktitut (Syllabics, Canada)" },
                { id: "iu-Latn", name: "Inuktitut (Latin)" },
                { id: "iu-Latn-CA", name: "Inuktitut (Latin, Canada)" },
                { id: "ja", name: "Japanese" },
                { id: "ja-JP", name: "Japanese (Japan)" },
                //{id:"jgo-CM",name:"Ngomba (Cameroon)"},
                //{id:"jmc-TZ",name:"Machame (Tanzania)"},
                //{id:"jv-Java-ID",name:"Javanese (Javanese, Indonesia)"},
                { id: "jv-Latn-ID", name: "Javanese (Indonesia)" },
                { id: "ka", name: "Georgian" },
                { id: "ka-GE", name: "Georgian (Georgia)" },
                //{id:"kab-DZ",name:"Kabyle (Algeria)"},
                //{id:"kam-KE",name:"Kamba (Kenya)"},
                //{id:"kde-TZ",name:"Makonde (Tanzania)"},
                //{id:"kea-CV",name:"Kabuverdianu (Cabo Verde)"},
                //{id:"khq-ML",name:"Koyra Chiini (Mali)"},
                //{id:"ki-KE",name:"Kikuyu (Kenya)"},
                { id: "kk", name: "Kazakh" },
                { id: "kk-KZ", name: "Kazakh (Kazakhstan)" },
                //{id:"kkj-CM",name:"Kako (Cameroon)"},
                { id: "kl", name: "Greenlandic" },
                { id: "kl-GL", name: "Greenlandic (Greenland)" },
                //{id:"kln-KE",name:"Kalenjin (Kenya)"},
                { id: "km", name: "Khmer" },
                { id: "km-KH", name: "Khmer (Cambodia)" },
                { id: "kn", name: "Kannada" },
                { id: "kn-IN", name: "Kannada (India)" },
                { id: "ko", name: "Korean" },
                //{id:"ko-KP",name:"Korean (North Korea)"},
                { id: "ko-KR", name: "Korean (Korea)" },
                { id: "kok", name: "Konkani" },
                { id: "kok-IN", name: "Konkani (India)" },
                //{id:"kr",name:"Kanuri"},
                //{id:"kr-NG",name:"Kanuri (Nigeria)"},
                //{id:"ks",name:"Kashmiri"},
                //{id:"ks-Arab",name:"Kashmiri (Perso-Arabic)"},
                //{id:"ks-Arab-IN",name:"Kashmiri (Perso-Arabic)"},
                //{id:"ks-Deva-IN",name:"Kashmiri (Devanagari, India)"},
                //{id:"ksb-TZ",name:"Shambala (Tanzania)"},
                //{id:"ksf-CM",name:"Bafia (Cameroon)"},
                //{id:"ksh-DE",name:"Ripuarian (Germany)"},
                { id: "ku", name: "Central Kurdish" },
                { id: "ku-Arab", name: "Central Kurdish (Arabic)" },
                { id: "ku-Arab-IQ", name: "Central Kurdish (Iraq)" },
                //{id:"ku-Arab-IR",name:"Kurdish (Perso-Arabic, Iran)"},
                //{id:"kw-GB",name:"Cornish (United Kingdom)"},
                { id: "ky", name: "Kyrgyz" },
                { id: "ky-KG", name: "Kyrgyz (Kyrgyzstan)" },
                //{id:"la",name:"Latin"},
                //{id:"la-001",name:"Latin (World)"},
                //{id:"lag-TZ",name:"Langi (Tanzania)"},
                { id: "lb", name: "Luxembourgish" },
                { id: "lb-LU", name: "Luxembourgish (Luxembourg)" },
                //{id:"lg-UG",name:"Ganda (Uganda)"},
                //{id:"lkt-US",name:"Lakota (United States)"},
                //{id:"ln-AO",name:"Lingala (Angola)"},
                //{id:"ln-CD",name:"Lingala (Congo DRC)"},
                //{id:"ln-CF",name:"Lingala (Central African Republic)"},
                //{id:"ln-CG",name:"Lingala (Congo)"},
                { id: "lo", name: "Lao" },
                { id: "lo-LA", name: "Lao (Lao P.D.R.)" },
                //{id:"lrc-IQ",name:"Northern Luri (Iraq)"},
                //{id:"lrc-IR",name:"Northern Luri (Iran)"},
                { id: "lt", name: "Lithuanian" },
                { id: "lt-LT", name: "Lithuanian (Lithuania)" },
                //{id:"lu-CD",name:"Luba-Katanga (Congo DRC)"},
                //{id:"luo-KE",name:"Luo (Kenya)"},
                //{id:"luy-KE",name:"Luyia (Kenya)"},
                { id: "lv", name: "Latvian" },
                { id: "lv-LV", name: "Latvian (Latvia)" },
                //{id:"mas-KE",name:"Masai (Kenya)"},
                //{id:"mas-TZ",name:"Masai (Tanzania)"},
                //{id:"mer-KE",name:"Meru (Kenya)"},
                //{id:"mfe-MU",name:"Morisyen (Mauritius)"},
                { id: "mg-MG", name: "Malagasy (Madagascar)" },
                //{id:"mgh-MZ",name:"Makhuwa-Meetto (Mozambique)"},
                //{id:"mgo-CM",name:"Meta' (Cameroon)"},
                { id: "mi", name: "Maori" },
                { id: "mi-NZ", name: "Maori (New Zealand)" },
                { id: "mk", name: "Macedonian (FYROM)" },
                { id: "mk-MK", name: "Macedonian (Former Yugoslav Republic of Macedonia)" },
                { id: "ml", name: "Malayalam" },
                { id: "ml-IN", name: "Malayalam (India)" },
                { id: "mn", name: "Mongolian" },
                { id: "mn-Cyrl", name: "Mongolian (Cyrillic)" },
                { id: "mn-MN", name: "Mongolian (Cyrillic, Mongolia)" },
                { id: "mn-Mong", name: "Mongolian (Traditional Mongolian)" },
                { id: "mn-Mong-CN", name: "Mongolian (Traditional Mongolian, PRC)" },
                { id: "mn-Mong-MN", name: "Mongolian (Traditional Mongolian, Mongolia)" },
                //{id:"mni",name:"Manipuri"},
                //{id:"mni-IN",name:"Manipuri (India)"},
                { id: "moh", name: "Mohawk" },
                { id: "moh-CA", name: "Mohawk (Mohawk)" },
                { id: "mr", name: "Marathi" },
                { id: "mr-IN", name: "Marathi (India)" },
                { id: "ms", name: "Malay" },
                { id: "ms-BN", name: "Malay (Brunei Darussalam)" },
                { id: "ms-MY", name: "Malay (Malaysia)" },
                //{id:"ms-SG",name:"Malay (Latin, Singapore)"},
                { id: "mt", name: "Maltese" },
                { id: "mt-MT", name: "Maltese (Malta)" },
                //{id:"mua-CM",name:"Mundang (Cameroon)"},
                { id: "my", name: "Burmese" },
                { id: "my-MM", name: "Burmese (Myanmar)" },
                //{id:"mzn-IR",name:"Mazanderani (Iran)"},
                //{id:"naq-NA",name:"Nama (Namibia)"},
                { id: "nb", name: "Norwegian (Bokmål)" },
                { id: "nb-NO", name: "Norwegian, Bokmål (Norway)" },
                //{id:"nb-SJ",name:"Norwegian, Bokmål (Svalbard and Jan Mayen)"},
                //{id:"nd-ZW",name:"North Ndebele (Zimbabwe)"},
                { id: "ne", name: "Nepali" },
                { id: "ne-IN", name: "Nepali (India)" },
                { id: "ne-NP", name: "Nepali (Nepal)" },
                { id: "nl", name: "Dutch" },
                //{id:"nl-AW",name:"Dutch (Aruba)"},
                { id: "nl-BE", name: "Dutch (Belgium)" },
                //{id:"nl-BQ",name:"Dutch (Bonaire, Sint Eustatius and Saba)"},
                //{id:"nl-CW",name:"Dutch (Curaçao)"},
                { id: "nl-NL", name: "Dutch (Netherlands)" },
                //{id:"nl-SR",name:"Dutch (Suriname)"},
                //{id:"nl-SX",name:"Dutch (Sint Maarten)"},
                //{id:"nmg-CM",name:"Kwasio (Cameroon)"},
                { id: "nn", name: "Norwegian (Nynorsk)" },
                { id: "nn-NO", name: "Norwegian, Nynorsk (Norway)" },
                //{id:"nnh-CM",name:"Ngiemboon (Cameroon)"},
                { id: "no", name: "Norwegian" },
                { id: "nqo-GN", name: "N'ko (Guinea)" },
                //{id:"nr-ZA",name:"South Ndebele (South Africa)"},
                { id: "nso", name: "Sesotho sa Leboa" },
                { id: "nso-ZA", name: "Sesotho sa Leboa (South Africa)" },
                //{id:"nus-SS",name:"Nuer (South Sudan)"},
                //{id:"nyn-UG",name:"Nyankole (Uganda)"},
                { id: "oc", name: "Occitan" },
                { id: "oc-FR", name: "Occitan (France)" },
                { id: "om", name: "Oromo" },
                { id: "om-ET", name: "Oromo (Ethiopia)" },
                //{id:"om-KE",name:"Oromo (Kenya)"},
                { id: "or", name: "Odia" },
                { id: "or-IN", name: "Odia (India)" },
                //{id:"os-GE",name:"Ossetian (Cyrillic, Georgia)"},
                //{id:"os-RU",name:"Ossetian (Cyrillic, Russia)"},
                { id: "pa", name: "Punjabi" },
                { id: "pa-Arab", name: "Punjabi (Arabic)" },
                { id: "pa-Arab-PK", name: "Punjabi (Islamic Republic of Pakistan)" },
                { id: "pa-IN", name: "Punjabi (India)" },
                //{id:"pap",name:"Papiamento"},
                //{id:"pap-029",name:"Papiamento (Caribbean)"},
                { id: "pl", name: "Polish" },
                { id: "pl-PL", name: "Polish (Poland)" },
                //{id:"prg-001",name:"Prussian (World)"},
                { id: "prs", name: "Dari" },
                { id: "prs-AF", name: "Dari (Afghanistan)" },
                { id: "ps", name: "Pashto" },
                { id: "ps-AF", name: "Pashto (Afghanistan)" },
                { id: "pt", name: "Portuguese" },
                { id: "pt-AO", name: "Portuguese (Angola)" },
                { id: "pt-BR", name: "Portuguese (Brazil)" },
                //{id:"pt-CV",name:"Portuguese (Cabo Verde)"},
                //{id:"pt-GW",name:"Portuguese (Guinea-Bissau)"},
                //{id:"pt-MO",name:"Portuguese (Macao SAR)"},
                //{id:"pt-MZ",name:"Portuguese (Mozambique)"},
                { id: "pt-PT", name: "Portuguese (Portugal)" },
                //{id:"pt-ST",name:"Portuguese (São Tomé and Príncipe)"},
                //{id:"pt-TL",name:"Portuguese (Timor-Leste)"},
                //{id:"quc",name:"K'iche'"},
                //{id:"quc-Latn",name:"K'iche'"},
                //{id:"quc-Latn-GT",name:"K'iche' (Guatemala)"},
                { id: "quz", name: "Quechua" },
                { id: "quz-BO", name: "Quechua (Bolivia)" },
                { id: "quz-EC", name: "Quechua (Ecuador)" },
                { id: "quz-PE", name: "Quechua (Peru)" },
                { id: "rm", name: "Romansh" },
                { id: "rm-CH", name: "Romansh (Switzerland)" },
                //{id:"rn-BI",name:"Rundi (Burundi)"},
                { id: "ro", name: "Romanian" },
                { id: "ro-MD", name: "Romanian (Moldova)" },
                { id: "ro-RO", name: "Romanian (Romania)" },
                //{id:"rof-TZ",name:"Rombo (Tanzania)"},
                { id: "ru", name: "Russian" },
                //{id:"ru-BY",name:"Russian (Belarus)"},
                //{id:"ru-KG",name:"Russian (Kyrgyzstan)"},
                //{id:"ru-KZ",name:"Russian (Kazakhstan)"},
                //{id:"ru-MD",name:"Russian (Moldova)"},
                { id: "ru-RU", name: "Russian (Russia)" },
                { id: "ru-UA", name: "Russian (Ukraine)" },
                { id: "rw", name: "Kinyarwanda" },
                { id: "rw-RW", name: "Kinyarwanda (Rwanda)" },
                //{id:"rwk-TZ",name:"Rwa (Tanzania)"},
                { id: "sa", name: "Sanskrit" },
                { id: "sa-IN", name: "Sanskrit (India)" },
                { id: "sah", name: "Sakha" },
                { id: "sah-RU", name: "Sakha (Russia)" },
                //{id:"saq-KE",name:"Samburu (Kenya)"},
                //{id:"sbp-TZ",name:"Sangu (Tanzania)"},
                { id: "sd", name: "Sindhi" },
                { id: "sd-Arab", name: "Sindhi (Arabic)" },
                { id: "sd-Arab-PK", name: "Sindhi (Islamic Republic of Pakistan)" },
                //{id:"sd-Deva-IN",name:"Sindhi (Devanagari, India)"},
                { id: "se", name: "Sami (Northern)" },
                { id: "se-FI", name: "Sami, Northern (Finland)" },
                { id: "se-NO", name: "Sami, Northern (Norway)" },
                { id: "se-SE", name: "Sami, Northern (Sweden)" },
                //{id:"seh-MZ",name:"Sena (Mozambique)"},
                //{id:"ses-ML",name:"Koyraboro Senni (Mali)"},
                //{id:"sg-CF",name:"Sango (Central African Republic)"},
                //{id:"shi-Latn-MA",name:"Tachelhit (Latin, Morocco)"},
                //{id:"shi-Tfng-MA",name:"Tachelhit (Tifinagh, Morocco)"},
                { id: "si", name: "Sinhala" },
                { id: "si-LK", name: "Sinhala (Sri Lanka)" },
                { id: "sk", name: "Slovak" },
                { id: "sk-SK", name: "Slovak (Slovakia)" },
                { id: "sl", name: "Slovenian" },
                { id: "sl-SI", name: "Slovenian (Slovenia)" },
                { id: "sma", name: "Sami (Southern)" },
                { id: "sma-NO", name: "Sami, Southern (Norway)" },
                { id: "sma-SE", name: "Sami, Southern (Sweden)" },
                { id: "smj", name: "Sami (Lule)" },
                { id: "smj-NO", name: "Sami, Lule (Norway)" },
                { id: "smj-SE", name: "Sami, Lule (Sweden)" },
                { id: "smn", name: "Sami (Inari)" },
                { id: "smn-FI", name: "Sami, Inari (Finland)" },
                { id: "sms", name: "Sami (Skolt)" },
                { id: "sms-FI", name: "Sami, Skolt (Finland)" },
                { id: "sn-Latn-ZW", name: "Shona (Latin, Zimbabwe)" },
                { id: "so", name: "Somali" },
                //{id:"so-DJ",name:"Somali (Djibouti)"},
                //{id:"so-ET",name:"Somali (Ethiopia)"},
                //{id:"so-KE",name:"Somali (Kenya)"},
                { id: "so-SO", name: "Somali (Somalia)" },
                { id: "sq", name: "Albanian" },
                { id: "sq-AL", name: "Albanian (Albania)" },
                //{id:"sq-MK",name:"Albanian (Macedonia, FYRO)"},
                //{id:"sq-XK",name:"Albanian (Kosovo)"},
                { id: "sr", name: "Serbian" },
                { id: "sr-Cyrl", name: "Serbian (Cyrillic)" },
                { id: "sr-Cyrl-BA", name: "Serbian (Cyrillic, Bosnia and Herzegovina)" },
                { id: "sr-Cyrl-ME", name: "Serbian (Cyrillic, Montenegro)" },
                { id: "sr-Cyrl-RS", name: "Serbian (Cyrillic, Serbia)" },
                //{id:"sr-Cyrl-XK",name:"Serbian (Cyrillic, Kosovo)"},
                { id: "sr-Latn", name: "Serbian (Latin)" },
                { id: "sr-Latn-BA", name: "Serbian (Latin, Bosnia and Herzegovina)" },
                { id: "sr-Latn-ME", name: "Serbian (Latin, Montenegro)" },
                { id: "sr-Latn-RS", name: "Serbian (Latin, Serbia)" },
                //{id:"sr-Latn-XK",name:"Serbian (Latin, Kosovo)"},
                //{id:"ss-SZ",name:"Swati (Swaziland)"},
                //{id:"ss-ZA",name:"Swati (South Africa)"},
                //{id:"ssy-ER",name:"Saho (Eritrea)"},
                { id: "st", name: "Southern Sotho" },
                //{id:"st-LS",name:"Sesotho (Lesotho)"},
                { id: "st-ZA", name: "Southern Sotho (South Africa)" },
                { id: "sv", name: "Swedish" },
                //{id:"sv-AX",name:"Swedish (Åland Islands)"},
                { id: "sv-FI", name: "Swedish (Finland)" },
                { id: "sv-SE", name: "Swedish (Sweden)" },
                { id: "sw", name: "Kiswahili" },
                //{id:"sw-CD",name:"Kiswahili (Congo DRC)"},
                { id: "sw-KE", name: "Kiswahili (Kenya)" },
                //{id:"sw-TZ",name:"Kiswahili (Tanzania)"},
                //{id:"sw-UG",name:"Kiswahili (Uganda)"},
                { id: "syr", name: "Syriac" },
                { id: "syr-SY", name: "Syriac (Syria)" },
                { id: "ta", name: "Tamil" },
                { id: "ta-IN", name: "Tamil (India)" },
                { id: "ta-LK", name: "Tamil (Sri Lanka)" },
                //{id:"ta-MY",name:"Tamil (Malaysia)"},
                //{id:"ta-SG",name:"Tamil (Singapore)"},
                { id: "te", name: "Telugu" },
                { id: "te-IN", name: "Telugu (India)" },
                //{id:"teo-KE",name:"Teso (Kenya)"},
                //{id:"teo-UG",name:"Teso (Uganda)"},
                { id: "tg", name: "Tajik" },
                { id: "tg-Cyrl", name: "Tajik (Cyrillic)" },
                { id: "tg-Cyrl-TJ", name: "Tajik (Cyrillic, Tajikistan)" },
                { id: "th", name: "Thai" },
                { id: "th-TH", name: "Thai (Thailand)" },
                { id: "ti", name: "Tigrinya" },
                { id: "ti-ER", name: "Tigrinya (Eritrea)" },
                { id: "ti-ET", name: "Tigrinya (Ethiopia)" },
                //{id:"tig-ER",name:"Tigre (Eritrea)"},
                { id: "tk", name: "Turkmen" },
                { id: "tk-TM", name: "Turkmen (Turkmenistan)" },
                { id: "tn", name: "Setswana" },
                { id: "tn-BW", name: "Setswana (Botswana)" },
                { id: "tn-ZA", name: "Setswana (South Africa)" },
                //{id:"to-TO",name:"Tongan (Tonga)"},
                { id: "tr", name: "Turkish" },
                //{id:"tr-CY",name:"Turkish (Cyprus)"},
                { id: "tr-TR", name: "Turkish (Turkey)" },
                { id: "ts", name: "Tsonga" },
                { id: "ts-ZA", name: "Tsonga (South Africa)" },
                { id: "tt", name: "Tatar" },
                { id: "tt-RU", name: "Tatar (Russia)" },
                //{id:"twq-NE",name:"Tasawaq (Niger)"},
                { id: "tzm", name: "Tamazight" },
                //{id:"tzm-Arab-MA",name:"Central Atlas Tamazight (Arabic, Morocco)"},
                { id: "tzm-Latn", name: "Tamazight (Latin)" },
                { id: "tzm-Latn-DZ", name: "Tamazight (Latin, Algeria)" },
                //{id:"tzm-Latn-MA",name:"Central Atlas Tamazight (Latin, Morocco)"},
                { id: "tzm-Tfng", name: "Tamazight (Tifinagh)" },
                { id: "tzm-Tfng-MA", name: "Central Atlas Tamazight (Tifinagh, Morocco)" },
                { id: "ug", name: "Uyghur" },
                { id: "ug-CN", name: "Uyghur (PRC)" },
                { id: "uk", name: "Ukrainian" },
                { id: "uk-UA", name: "Ukrainian (Ukraine)" },
                { id: "ur", name: "Urdu" },
                { id: "ur-IN", name: "Urdu (India)" },
                { id: "ur-PK", name: "Urdu (Islamic Republic of Pakistan)" },
                { id: "uz", name: "Uzbek" },
                //{id:"uz-Arab-AF",name:"Uzbek (Perso-Arabic, Afghanistan)"},
                { id: "uz-Cyrl", name: "Uzbek (Cyrillic)" },
                { id: "uz-Cyrl-UZ", name: "Uzbek (Cyrillic, Uzbekistan)" },
                { id: "uz-Latn", name: "Uzbek (Latin)" },
                { id: "uz-Latn-UZ", name: "Uzbek (Latin, Uzbekistan)" },
                //{id:"vai-Latn-LR",name:"Vai (Latin, Liberia)"},
                //{id:"vai-Vaii-LR",name:"Vai (Vai, Liberia)"},
                //{id:"ve",name:"Venda"},
                //{id:"ve-ZA",name:"Venda (South Africa)"},
                { id: "vi", name: "Vietnamese" },
                { id: "vi-VN", name: "Vietnamese (Vietnam)" },
                //{id:"vo-001",name:"Volapük (World)"},
                //{id:"vun-TZ",name:"Vunjo (Tanzania)"},
                //{id:"wae-CH",name:"Walser (Switzerland)"},
                //{id:"wal-ET",name:"Wolaytta (Ethiopia)"},
                { id: "wo", name: "Wolof" },
                { id: "wo-SN", name: "Wolof (Senegal)" },
                { id: "xh", name: "isiXhosa" },
                { id: "xh-ZA", name: "isiXhosa (South Africa)" },
                //{id:"xog-UG",name:"Soga (Uganda)"},
                //{id:"yav-CM",name:"Yangben (Cameroon)"},
                //{id:"yi",name:"Yiddish"},
                //{id:"yi-001",name:"Yiddish (World)"},
                { id: "yo", name: "Yoruba" },
                //{id:"yo-BJ",name:"Yoruba (Benin)"},
                { id: "yo-NG", name: "Yoruba (Nigeria)" },
                { id: "zgh-Tfng-MA", name: "Standard Moroccan Tamazight (Tifinagh, Morocco)" },
                { id: "zh", name: "Chinese" },
                { id: "zh-CN", name: "Chinese (Simplified, PRC)" },
                { id: "zh-Hans", name: "Chinese (Simplified)" },
                //{id:"zh-Hans-HK",name:"Chinese (Simplified Han, Hong Kong SAR)"},
                //{id:"zh-Hans-MO",name:"Chinese (Simplified Han, Macao SAR)"},
                { id: "zh-Hant", name: "Chinese (Traditional)" },
                { id: "zh-HK", name: "Chinese (Traditional, Hong Kong S.A.R.)" },
                { id: "zh-MO", name: "Chinese (Traditional, Macao S.A.R.)" },
                { id: "zh-SG", name: "Chinese (Simplified, Singapore)" },
                { id: "zh-TW", name: "Chinese (Traditional, Taiwan)" },
                { id: "zu", name: "isiZulu" },
                { id: "zu-ZA", name: "isiZulu (South Africa)" }
        ];

        if (culture && culture.indexOf("ar-") != -1)
            d = d.map(function (item) {
                return { id: item.id, name: (culture && culture.indexOf("ar-") != -1 && item.arName ? item.arName : item.name) };
            });
        return d;
    }
    return { getList: getList }
}();